### ISSUE TITLE
Route vs. Routes vs. SiteMap confusion

### ISSUE THREAD

**Issue by matovitch** [elm-community/elm-route#6]
Hello !

First of all nice job for this package ! :+1: 

There is an error within the README.md where the example mix up Route the module with Route the type with SiteMap the undefined type. And the match function in Route vs. Routes modules in the end is confusing as well (Routes isn't defined anywhere as well). I don't know how you would rather named them so I didn't proposed a PR but these details bugged me for a while.

Thanks again for your great work !

Regards,

Camille

**Comment by Bogdanp** [comment]
Thanks and apologies for the confusion, I'd renamed `Sitemap` to `Route` at one point, but it seems like I had missed some instances.

`Routes` refers to the _module_ those routes are defined in, while `Route` is the ADT for concrete route values.

**Comment by matovitch** [comment]
That was quick ! No problem for the confusion I looked at the example and it became clear.
