### ISSUE TITLE
Package not published to elm-community

### ISSUE THREAD

**Issue by nanoxd** [elm-community/elm-route#8]
I noticed with the repo change, the package itself isn't published to `elm-community/elm-route`. I'm new to the Elm community, will it be moved to the package namespace at some point? If so, I can make a pull request to update the readme 😄

Thanks for the project! It's been great to have this library to think about how to structure routes.

**Comment by gjaldon** [comment]
Package is now published at http://package.elm-lang.org/packages/elm-community/elm-route/latest
